apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: backend  # La política aplica a los pods etiquetados como "backend"
  policyTypes:
  - Ingress  # Esta política regula solo el tráfico de entrada
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend  # Solo el frontend puede acceder al backend
    ports:
    - protocol: TCP
      port: 5000  # Permite tráfico al puerto 5000 del backend
