apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: monsterultrafiesta/backend:latest  # Docker Hub image
        ports:
        - containerPort: 5000  # Backend exposes port 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: LoadBalancer  # Expose externally
  loadBalancerIP: 192.168.99.100  # Set a static IP (example IP)
  ports:
    - protocol: TCP
      port: 5000  # External port
      targetPort: 5000  # Redirects to backend container's port
