apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: monsterultrafiesta/backend:latest  # Imagen de Docker Hub
        ports:
        - containerPort: 5000  # El backend expone el puerto 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000  # El puerto del servicio dentro del clúster
      targetPort: 5000  # Redirige al puerto 5000 del contenedor backend
  type: ClusterIP  # Solo accesible dentro del clúster
